language: java
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
env:
 - TEST_DIR=engine
 - TEST_DIR=player
 - TEST_DIR=ai
 - TEST_DIR=server
script: cd $TEST_DIR && mvn install -B -V && mvn test -B